apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles:
    -rolearn: arn:aws:iam::846182034292:role/nginx-nodegroup-NodeInstanceRole-1ADKJ1L95FU6
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        -system:nodes