version: '3'
services:
    platform:
        container_name: web-sg
        image: 046368006331.dkr.ecr.ap-southeast-1.amazonaws.com/web-sg:PLATFORM_VERSION
        volumes:
            - /home/CONTAINER_USER/.legaldocuments/:/usr/share/nginx/html/legaldocuments/
        ports:
            - "8088:80"
        restart: unless-stopped